%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%
% Import_N2_LES_diss.m
%
% Script for importing data from the following text file:
%
%    /Users/Andy/Cruises_Research/IWISE/Analysis/S9/Dissipation/OverturnsBiases/LES/N2turbdiss_ZT.dat
%
% Auto-generated by MATLAB on 2015/02/19 12:57:29
%
% From Masoud: "The second file is "N2turbdiss_ZT.dat" saving turbulent
% dissipation in time. It is an ASCII file having year_time,Z,turbulence dissipation and log scale of that"
%
% 19 Feb. 2015
%
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%%

clear ; close all

% Initialize variables.
filename = '/Users/Andy/Cruises_Research/IWISE/Analysis/S9/Dissipation/OverturnsBiases/LES/N2turbdiss_ZT.dat';
startRow = 11;

% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%16f%17f%17f%f%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

% Allocate imported array to column variable names
yday0 = dataArray{:, 1};
z0 = dataArray{:, 2};
eps = dataArray{:, 3};
logeps = dataArray{:, 4};

% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;

% put data into a structure
N2diss=struct();
%N2diss.yday=yearday;
%N2diss.z=z*100;
N2diss.eps=eps;
N2diss.logeps=logeps;

clear yearday z eps logeps

% Reshape data into usual depth-time grid

clear yday z eps2 logeps2 Nt
yday=unique(yday0);
z=unique(z0);

eps2=reshape(N2diss.eps,length(z),length(yday));
logeps2=reshape(N2diss.logeps,length(z),length(yday));

eps2=nan*ones(length(z),length(yday));
Nt=length(yday);
for whz=1:length(z)
logeps2(whz,:)=N2diss.logeps( (whz-1)*Nt +1: whz*Nt);
eps2(whz,:)=N2diss.eps( (whz-1)*Nt +1: whz*Nt);
end

figure(11);clf
ezpc(yday,z*100,log10(abs(eps2)))
%ezpc(yday,z,eps2)
colorbar
caxis([-9 -4])
axis xy;
cmap=jet;
colormap([ 0.9*[1 1 1] ; cmap])

%
%
N2diss.yday=yday;
N2diss.z=abs(z)*100;
N2diss.eps=abs(eps2);
N2diss.logeps=logeps2;
fname='/Users/Andy/Cruises_Research/IWISE/Analysis/S9/Dissipation/OverturnsBiases/LES/N2diss.mat'
save(fname,'N2diss')

%%

clear ; close all

load('/Users/Andy/Cruises_Research/IWISE/Analysis/S9/Dissipation/OverturnsBiases/LES/N2diss.mat')

figure(11);clf
ezpc(N2diss.yday,N2diss.z,log10(abs(N2diss.eps)))
%ezpc(yday,z,eps2)
cb=colorbar
cb.Label.String='log_{10}\epsilon'
caxis([-9 -4])
%axis xy;
cmap=jet;
colormap([ 0.9*[1 1 1] ; cmap])
xlabel('Yearday')
ylabel('Depth (m)')


%%